"use strict"// treats all JS code as newer version 
//  alert (3+3) error as we are using nodejs not browser as engine
// code readability should be high no unnecessary spaces in between 
console.log(3+3)
let name ="hitesh"   // string
let age =18          // number
let  isLoggedin = false // boolean

 
// DATATYPES IN JS:
// 1.string => ""
// 2.number => values upto 2^53
// 3.bigint => big numbers usen in large website like reddit facebook
// 4.boolean => true/false
// 5.null = standalone value hai
// 6.undefined => no value assigned
// 7.symbol => they are unique . maily used with REACT
// 8. typeof => tells the type of datatype of an element

 console.log(typeof undefined)  // undefined
 console.log(typeof null) //object -> output